#!/bin/sh

if [ -x /usr/bin/apt-key ]; then
		# remove obsolete/ revoked keys
		for i in $(gpg --with-colons /usr/share/keyrings/kanotix-keyring.gpg 2>/dev/null | grep ^pub | cut -d\: -f 5); do
			if ! gpg --with-colons  /usr/share/keyrings/kanotix-archive-keyring.gpg 2>/dev/null | grep -q "$i" 2>/dev/null; then
				/usr/bin/apt-key del "$i"
			fi
		done

		/usr/bin/apt-key update || true
fi

#DEBHELPER#

