#!/bin/sh

if [ -x /usr/bin/apt-key ]; then
	# add new keys
	/usr/bin/apt-key add /usr/share/keyrings/kanotix-archive-keyring.gpg

	# remove obsolete/ revoked keys
	if [ -s /usr/share/keyrings/kanotix-archive-removed-keys.gpg ]; then
		for i in $(gpg --with-colons /usr/share/keyrings/kanotix-archive-removed-keys.gpg | grep ^pub | cut -d\: -f 5); do
			/usr/bin/apt-key del "$i"
		done
	fi
fi

#DEBHELPER#

